spring.application.name=evaluacionfinal

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/evaluacionfinal_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicializacion de datos
spring.jpa.defer-datasource-initialization=true

# Servidor
server.port=8081